language: php
os: linux
dist: bionic

env:
  global:
    - COMPOSER_INSTALL_FLAGS="--no-interaction --no-progress --prefer-dist"
    - COMPOSER_UPDATE_FLAGS="--no-interaction --no-progress --prefer-dist"

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_UPDATE_FLAGS="--prefer-lowest ${COMPOSER_UPDATE_FLAGS}"
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: CS=1
    - php: 8.0
    - php: nightly
      env: STABILITY=dev SYMFONY_DEPRECATIONS_HELPER=weak
      install:
        - composer config platform.php 7.4.99
        - make vendor
      script:
        - make phpunit

  allow_failures:
    - php: nightly

cache:
  directories:
    - ${HOME}/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - if ! [ -z "${STABILITY}" ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master

install:
  - make vendor

script:
  - make tests-without-cs
  - if [[ ${CS} == 1 ]]; then make cs-check; fi
